# Generated by Django 5.1.8 on 2026-05-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do DFD')),
                ('numero_processo', models.CharField(blank=True, max_length=50, verbose_name='Número do Processo')),
                ('link_publico', models.URLField(blank=True, verbose_name='Link Público')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DFD',
                'verbose_name_plural': 'DFDs',
                'ordering': ['-criado_em'],
            },
        ),
    ]
