# Generated by Django 5.1.8 on 2026-05-17 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0002_initial'),
        ('dfd', '0001_initial'),
        ('grupos_contratacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dfds_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dfds', to='grupos_contratacao.grupocontratacao', verbose_name='Grupo de Contratação'),
        ),
        migrations.AddField(
            model_name='dfd',
            name='itens_demanda',
            field=models.ManyToManyField(blank=True, related_name='dfds', to='demandas.itemdemanda', verbose_name='Itens de Demanda'),
        ),
    ]
