# Generated by Django 5.1.8 on 2026-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_sincronizar_dados_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemanda',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do Solicitante'),
        ),
    ]
