# Generated by Django 5.1.8 on 2026-05-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos_contratacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_catmat_catser', models.CharField(blank=True, max_length=30, verbose_name='Código CATMAT/CATSER')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Estimado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_catalogo', to='grupos_contratacao.grupocontratacao', verbose_name='Grupo de Contratação')),
            ],
            options={
                'verbose_name': 'Item do Catálogo',
                'verbose_name_plural': 'Itens do Catálogo',
                'ordering': ['nome'],
            },
        ),
    ]
