# Generated by Django 5.1.8 on 2026-05-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('servico', 'Serviço')], help_text='Material ou Serviço.', max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Estimado Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Calculado: quantidade × valor estimado unitário.', max_digits=14, verbose_name='Valor Total')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20, verbose_name='Prioridade')),
                ('justificativa_prioridade', models.TextField(verbose_name='Justificativa da Prioridade')),
                ('justificativa_necessidade', models.TextField(verbose_name='Justificativa da Necessidade')),
                ('indicacao_orcamentaria', models.CharField(max_length=200, verbose_name='Indicação Orçamentária')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_validacao', 'Aguardando Validação'), ('devolvida', 'Devolvida'), ('validada', 'Validada'), ('consolidada', 'Consolidada no DFD'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item de Demanda',
                'verbose_name_plural': 'Itens de Demanda',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.PositiveIntegerField(verbose_name='Ano de Referência')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_validacao', 'Aguardando Validação'), ('devolvida', 'Devolvida'), ('validada', 'Validada'), ('consolidada', 'Consolidada no DFD'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='unidades.unidade', verbose_name='Unidade Solicitante')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
