# Generated by Django 5.1.8 on 2026-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_validacao', 'Aguardando Validação'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemdemanda',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_validacao', 'Aguardando Validação'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=30, verbose_name='Status'),
        ),
    ]
