# Generated by Django 5.1.8 on 2026-08-15

from django.db import migrations, models


def preservar_itens_duplicados_como_manuais(apps, schema_editor):
    """Libera a chave de catálogo repetida sem apagar itens históricos."""
    ItemDemanda = apps.get_model("demandas", "ItemDemanda")
    vistos = set()
    duplicados = []
    for item in (
        ItemDemanda.objects.exclude(item_catalogo_id=None)
        .order_by("demanda_id", "item_catalogo_id", "criado_em", "id")
        .only("id", "demanda_id", "item_catalogo_id")
    ):
        chave = (item.demanda_id, item.item_catalogo_id)
        if chave in vistos:
            duplicados.append(item.id)
        else:
            vistos.add(chave)
    if duplicados:
        ItemDemanda.objects.filter(id__in=duplicados).update(item_catalogo_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("demandas", "0007_itemdemanda_dfd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdemanda",
            name="justificativa_prioridade",
            field=models.TextField(
                blank=True,
                verbose_name="Justificativa da Prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="itemdemanda",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("aguardando_validacao", "Aguardando Validação"),
                    ("devolvida", "Devolvida"),
                    ("validada", "Validada"),
                    ("vinculada_dfd", "Vinculada ao DFD"),
                    ("cancelada", "Cancelada"),
                ],
                default="rascunho",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(
            preservar_itens_duplicados_como_manuais,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="itemdemanda",
            constraint=models.UniqueConstraint(
                fields=("demanda", "item_catalogo"),
                name="uniq_item_catalogo_demanda",
            ),
        ),
    ]
