# Generated by Django 5.2.17 on 2026-08-25 12:55

from django.conf import settings
from django.db import migrations

UNIDADES_INICIAIS = [
    {"codigo": "sti", "sigla": "STI", "nome": "Superintendência de Tecnologia da Informação"},
    {"codigo": "prad", "sigla": "PRAD", "nome": "Pró-Reitoria de Administração"},
    {"codigo": "preuni", "sigla": "PREUNI", "nome": "Prefeitura Universitária"},
    {"codigo": "ccn", "sigla": "CCN", "nome": "Centro de Ciências da Natureza"},
    {"codigo": "cchl", "sigla": "CCHL", "nome": "Centro de Ciências Humanas e Letras"},
    {"codigo": "cce", "sigla": "CCE", "nome": "Centro de Ciências da Educação"},
    {"codigo": "ccs", "sigla": "CCS", "nome": "Centro de Ciências da Saúde"},
    {"codigo": "cca", "sigla": "CCA", "nome": "Centro de Ciências Agrárias"},
    {"codigo": "picos", "sigla": "CSHNB", "nome": "Campus Senador Helvídio Nunes de Barros (Picos)"},
    {"codigo": "bomjesus", "sigla": "CPCE", "nome": "Campus Professora Cinobelina Elvas (Bom Jesus)"},
    {"codigo": "floriano", "sigla": "CAFS", "nome": "Campus Amílcar Ferreira Sobral (Floriano)"},
]

def criar_unidades_iniciais(apps, schema_editor):
    # O banco criado pelo runner de testes deve permanecer vazio para que as
    # fixtures possam criar livremente as unidades de cada cenário. A
    # migração continua populando bancos de desenvolvimento e produção.
    if getattr(settings, "TESTING", False):
        return

    Unidade = apps.get_model('unidades', 'Unidade')
    for uni in UNIDADES_INICIAIS:
        Unidade.objects.get_or_create(
            codigo=uni["codigo"],
            defaults={
                "sigla": uni["sigla"],
                "nome": uni["nome"]
            }
        )

def reverter_unidades_iniciais(apps, schema_editor):
    Unidade = apps.get_model('unidades', 'Unidade')
    codigos = [uni["codigo"] for uni in UNIDADES_INICIAIS]
    Unidade.objects.filter(codigo__in=codigos).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_unidades_iniciais, reverter_unidades_iniciais),
    ]
