# Generated by Django 5.1.8 on 2026-05-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoContratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_administrados', to='unidades.unidade', verbose_name='Unidade Administradora')),
            ],
            options={
                'verbose_name': 'Grupo de Contratação',
                'verbose_name_plural': 'Grupos de Contratação',
                'ordering': ['nome'],
            },
        ),
    ]
