# Generated by Django 5.1.8 on 2026-05-17 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('validado', 'Validado'), ('devolvido', 'Devolvido')], max_length=20, verbose_name='Ação')),
                ('comentario', models.TextField(blank=True, help_text='Obrigatório em caso de devolução.', verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='demandas.itemdemanda', verbose_name='Item de Demanda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador')),
            ],
            options={
                'verbose_name': 'Validação',
                'verbose_name_plural': 'Validações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
